### ISSUE TITLE
ERROR ON MAKE SERVER

### ISSUE THREAD

**Issue by NoisyGolden** [Xart3mis/AKILT#19]
ubuntu@vps-0ee9bec3:~/git/AKILT$ make server
go env -w GOOS=windows
go env -w GOARCH=amd64
go build -ldflags "-w -s" -o .\\Server\\bin\\server-windows-amd64.exe .\\Server\\
malformed import path ".\\Server\\": invalid char '\\'
make: *** [Makefile:21: server] Error 1

**Comment by Xart3mis** [comment]
replace the backslashes in the makefile to regular slashes
